### ISSUE TITLE
Catkin build issue

### ISSUE THREAD

**Issue by an99990** [engcang/oakd-ros-simple#1]
HI,
I am trying to build this package and am facing some issues with catkin build.

```
catkin build --unbuilt -Ddepthai_DIR=catkin_ws/src/oakd-ros-simple/depthai-core/build/install/lib/cmake/depthai
The build space at '/home/ubuntu/catkin_ws/build' was previously built by 'catkin_make'. Please remove the build space or pick a different build space.
```
Building only oakd-ros-simple gives me the same issue.

please help me resolve this issue

**Comment by engcang** [comment]
Hi @an99990 .

1. I think you should delete every folder except `src` within `catkin_ws` and then catkin build, Because you `catkin_make` the folder before, as error message says:
```
The build space at '/home/ubuntu/catkin_ws/build' was previously built by 'catkin_make'. Please remove the build space or pick a different build space.
```

2. The path `-Ddepthai_DIR=catkin_ws/src/oakd-ros-simple/depthai-core/build/install/lib/cmake/depthai`  should be in `absolute path`. For example, `-Ddepthai_DIR=/home/mason/catkin_ws/src/oakd-ros-simple/depthai-core/build/install/lib/cmake/depthai`

**Comment by an99990** [comment]
hi @engcang , 
i have deleted the build and devel folder and here what i get using this command :

`catkin build -Ddepthai_DIR=/home/ubuntu/catkin_ws/src/oakd-ros-simple/depthai-core/build/install/lib/cmake/depthai
`

```
Errors     << oakd_ros:cmake /home/ubuntu/catkin_ws/logs/oakd_ros/build.cmake.001.log
CMake Warning at /home/ubuntu/catkin_ws/src/oakd-ros-simple/CMakeLists.txt:13 (message):
  depthai FOUND, Version:2.15.0 directory:
  /home/ubuntu/catkin_ws/src/oakd-ros-simple/depthai-core/build/install/lib/cmake/depthai
CMake Warning at /home/ubuntu/catkin_ws/src/oakd-ros-simple/CMakeLists.txt:29 (message):
  OpenCV FOUND, Version:3.2.0 directory: /usr/include/usr/include/opencv
CMake Error at /home/ubuntu/catkin_ws/src/oakd-ros-simple/CMakeLists.txt:57 (add_executable):
  Target "oakd_ros_node" links to target "depthai::opencv" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

**Comment by engcang** [comment]
@an99990 

Do you have `libdepthai-opencv.so` file in `/home/ubuntu/catkin_ws/src/oakd-ros-simple/depthai-core/build/install/lib` folder?

**Comment by an99990** [comment]
not sure, how could i install it. doesnt it come with opencv ?

**Comment by engcang** [comment]
@an99990 
What do you mean "not sure".
You go to that directory and see if there exist the file or not yourself dude.

If you don't have the file, you did not follow the instruction here - https://github.com/engcang/oakd-ros-simple#how-to-install

It should be generated with 
$ cmake .. -DBUILD_SHARED_LIBS=ON
$ make install

**Comment by an99990** [comment]
i dont have it, i just checked in the folder. but i did follow the instructions

**Comment by an99990** [comment]
i have libdepthai-core.so

**Comment by engcang** [comment]
You have to get both of libdepthai-core.so and libdepthai-opencv.so

1. I think you only have Opencv 3.2.0 and that is why you could not get one. As far as I know, depthai needs Opencv version 4.X

2. If you don't want to install OpenCV 4.X, then try to edit this line - https://github.com/engcang/oakd-ros-simple/blob/main/CMakeLists.txt#L58

```python
#target_link_libraries(${PROJECT_NAME}_node ${catkin_LIBRARIES} ${OpenCV_LIBS} depthai::core depthai::opencv)
target_link_libraries(${PROJECT_NAME}_node ${catkin_LIBRARIES} ${OpenCV_LIBS} depthai::core)
```

I did not try this before, so I am not sure if it can be built with that or not.

**Comment by an99990** [comment]
Hi @engcang  so i just upgrade opencv4 and python. rebuilt the entire thing, but still am unable to see the libdepthai-opencv.so

**Comment by engcang** [comment]
@an99990 
Hmmmm... weird. But sadly, that is out of my range. That is totally related to [`depthai-core`](https://github.com/luxonis/depthai-core). 

If you look into this line of `depth-core`, It tries to build depthai-opencv library.

[line1](https://github.com/luxonis/depthai-core/blob/5cafb68da68e7242e94c7ebd038baa919f7e4835/CMakeLists.txt#L259)
[line2](https://github.com/luxonis/depthai-core/blob/5cafb68da68e7242e94c7ebd038baa919f7e4835/CMakeLists.txt#L438-L485)

So you have to try to build depthai-core again with
```shell
$ rm -r ~/.hunter ###very important

$ cd oakd-ros-simple/depthai-core
$ mkdir build && cd build
$ cmake .. -DBUILD_SHARED_LIBS=ON -DDEPTHAI_OPENCV_SUPPORT=ON

$ make install
```

If you still cannot get `libdepthai-opencv.so` file, then it means your configuration cannot find "opencv_core" "opencv_imgproc" within the cmake process. and that is why you cannot get it.
Then, I think it will be better for you to ask a question regarding this the official depthai-core developer.
But I think you slightly mis-installed OpenCV and that could be the reason that your cmake cannot find OpenCV properly. Make sure you have it well.

**Comment by engcang** [comment]
@an99990 

> Hi @engcang so i just upgrade opencv4 and python. rebuilt the entire thing, but still am unable to see the libdepthai-opencv.so

Oh, by the way, you mentioned you "upgrade opencv4 and python". That looks suspicious for me.
How did you install OpenCV? Did you only install python and python-opencv via pip install???
That cannot be linked to cmake and cannot be built to libdepthai-opencv.so.

You have to install OpenCV properly...
Refer to my other repository - [here](https://github.com/engcang/vins-application#-opencv-with-cuda-and-cudnn)

**Comment by an99990** [comment]
no this is the process that i followed:

```
$ wget -O opencv.zip https://github.com/opencv/opencv/archive/4.0.0.zip
$ wget -O opencv_contrib.zip 
$ unzip opencv.zip
$ unzip opencv_contrib.zip

$ cd ~/opencv-4.0.0
$ mkdir build
$ cd build
cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
    -D ENABLE_NEON=ON \
    -D ENABLE_VFPV3=ON \
    -D BUILD_TESTS=OFF \
    -D OPENCV_ENABLE_NONFREE=ON \
    -D INSTALL_PYTHON_EXAMPLES=OFF \
    -D BUILD_EXAMPLES=OFF ..

```

**Comment by engcang** [comment]
@an99990 Did you do `make` and `sudo make install` after cmake?
do you have
`/usr/local/lib/libopencv_imgproc.so` and `/usr/local/lib/libopencv_core.so` ?
Or, you mis-installed OpenCV.

If you have both, but you still cannot generate `libdepthai-opencv.so`, then please publish new issue in the official `depthai-core` Github: https://github.com/luxonis/depthai-core

**Comment by an99990** [comment]
i have libopencv_core.so and libopencv_imgproc.so. I will make a fresh install and try again

**Comment by an99990** [comment]
so i finally got the `libdepthai-opencv.so` but catkin_build fails on oak package @engcang 
```
Errors     << oakd_ros:make /home/ubuntu/catkin_ws/logs/oakd_ros/build.make.000.log
In file included from /home/ubuntu/catkin_ws/src/oakd-ros-simple/src/main_ros.cpp:1:0:
/home/ubuntu/catkin_ws/src/oakd-ros-simple/include/main.h:21:10: fatal error: oakd_ros/bboxes.h: No such file or directory
 #include <oakd_ros/bboxes.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/oakd_ros_node.dir/src/main_ros.cpp.o] Error 1
make[1]: *** [CMakeFiles/oakd_ros_node.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by an99990** [comment]
will close this and open new issue about bbox.h
