### ISSUE TITLE
no devices available

### ISSUE THREAD

**Issue by an99990** [engcang/oakd-ros-simple#3]
Hi @engcang ,
so when i launch the node, i get no available devices

```
what():  No available devices
Stack trace (most recent call last):
#0    Source "../sysdeps/unix/sysv/linux/raise.c", line 51, in raise [0xffffb8134598]
Aborted (Signal sent by tkill() 2982 1000)
[oakd_ros_node-1] process has died [pid 2982, exit code -6, cmd /home/ubuntu/catkin_ws/devel/lib/oakd_ros/oakd_ros_node __name:=oakd_ros_node __log:=/home/ubuntu/.ros/log/1c0a11b4-39f5-11ed-a5e3-dca632d50a38/oakd_ros_node-1.log].
log file: /home/ubuntu/.ros/log/1c0a11b4-39f5-11ed-a5e3-dca632d50a38/oakd_ros_node-1*.log
```

**Comment by engcang** [comment]
I also suffered the problem today and solved it by changing the USB3 cable.
I recommend to check `$ lsusb`, `$ dmesg -w`, and run `depthai_demo.py` from [official demo](https://github.com/luxonis/depthai) first. If you cannot run official demo, solve the cable and connection issue first. It is not the case of my code.
