### ISSUE TITLE
X_LINK_DEVICE_NOT_FOUND

### ISSUE THREAD

**Issue by Devin-Pi** [engcang/oakd-ros-simple#4]
The corresponding error message is shown below.
![image](https://user-images.githubusercontent.com/89199086/205547329-e8631e06-3f37-4b51-b072-60bc9503acaa.png)
Actually, I can find and use OAK-D in the docker according to the official python examples. 
The corresponding information about the environment is listed as follows:
Docker container environment: docker run --gpus all -it --ipc=host --net=host --privileged -e DISPLAY=unix$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix:rw -e NVIDIA_DRIVER_CAPABILITIES=all introlab3it/rtabmap:focal /bin/bash
Ubuntu: 20.04-LTS
Device: OAK-D-PRO-W
Could you please help me to solve this problem? Many thanks for helping me!

**Comment by engcang** [comment]
@RendongPi 
Hi. Sorry for late.
This code assumes you installed every dependencies outside the Docker, not inside the Docker.
Did you follow the [how to install](https://github.com/engcang/oakd-ros-simple#how-to-install) to install everything properly?

Thanks.

**Comment by engcang** [comment]
@RendongPi 
Hi. Did you install every dependencies outside Docker and try again?

Thanks.

**Comment by engcang** [comment]
Since there has been no further updates, closing the issue.

P.S. I also suffered the problem today and solved it by changing the USB3 cable.
I recommend to check `$ lsusb`, `$ dmesg -w`, and run `depthai_demo.py` from [official demo](https://github.com/luxonis/depthai) first. If you cannot run official demo, solve the cable and connection issue first. It is not the case of my code.

**Comment by Devin-Pi** [comment]
> Since there has been no further updates, closing the issue.
> 
> P.S. I also suffered the problem today and solved it by changing the USB3 cable. I recommend to check `$ lsusb`, `$ dmesg -w`, and run `depthai_demo.py` from [official demo](https://github.com/luxonis/depthai) first. If you cannot run official demo, solve the cable and connection issue first. It is not the case of my code.

Thanks for your reply!
